### ISSUE TITLE
force fetch -d does not override the directory as documented in help example

### ISSUE THREAD

**Issue by diligent176** [ForceCLI/force#213]
How I'm using it:

> force fetch -d=dirname -t=CustomObject -n=Bank_Account__c
> OR
> force fetch -d=c:\temp\obj -t=CustomObject -n=Bank_Account__c

It always retrieves to the default "metadata" directory in the same folder as force.exe.
The help example shows that -d should override the output directory.

Also, if you run the command twice, once against objectA__c, then again on objectB__c, the package.XML is not updated or overwritten.  The package manifest only includes objectA, not objectB.

**Comment by diligent176** [comment]
This is a great tool but needs more development activity.  Lots of commits and pull requests but no release since build 0.22.36 several months ago...   If I had the skills I would pitch in, but go language is foreign to me.

**Comment by dcarroll** [comment]
Sorry. On holiday.

Dave Carroll

On Jan 4, 2016, at 11:48 AM, Jason Bellis <notifications@github.com> wrote:

This is a great tool but needs more development activity. Lots of commits
and pull requests but no release since build 0.22.36 several months ago...
If I had the skills I would pitch in, but go language is foreign to me.

—
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/issues/213#issuecomment-168781245>.

**Comment by ericrsmith35** [comment]
I have the same issue with the -d open on fetch.  I'm running on a Windows machine.  Any resolution?

**Comment by ImJohnMDaniel** [comment]
I also am affected by this issue.  I am no expert in the Go language, but in reading the fetch.go file, it looks to me like the "-d" switch has not been implemented yet.  Is that the case?

**Comment by cwarden** [comment]
Opened #489 to implement this.

**Comment by cwarden** [comment]
Addressed in #489
