### ISSUE TITLE
Sanity check please: `force login` expected behaviour

### ISSUE THREAD

**Issue by danielsokolowski** [ForceCLI/force#263]
Hello all,

Need to confirm what the expected behavior is, I have the latest `force_windows_386.exe` and I can't figure out how to login.
1. When I do `force_windows_386.exe login -i=test` a browser window open up to the salesforce login page but I can not login, tried username with pass, and username with passtoken
2. When I do `force_windows_386.exe login -i=*********--devcms.cs13.my.salesforce.com` I get `ERROR: no such endpoint type`
3. When I do `force login -u=daniel.sokolowski@stantive.com.devcms -p=<passandtoken>` it does login.

Why is approach 1 not working?, why is option 2 giving me no such endpoint, I'd like to make a small script to send to the client so the ideal would be for them to login using option 1.

**Comment by dcarroll** [comment]
Are you using a sandbox username?

Dave Carroll

On Mar 1, 2016, at 6:17 AM, Daniel Sokolowski <notifications@github.com>
wrote:

Hello all,

Need to confirm what the expected behavior is, I have the latest
force_windows_386.exe and I can't figure out how to login.

   1.

   When I do force_windows_386.exe login -i=test a browser window open up
   to the salesforce login page but I can not login, tried username with pass,
   and username with passtoken
   2.

   When I do force_windows_386.exe login -i=*********--
   devcms.cs13.my.salesforce.com I get ERROR: no such endpoint type
   3.

   When I do force login -u=daniel.sokolowski@stantive.com.devcms
   -p=<passandtoken> it does login.

Why is approach 1 not working?, why is option 2 giving me no such endpoint,
I'd like to make a small script to send to the client so the ideal would be
for them to login using option 1.

—
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/issues/263>.

**Comment by dcarroll** [comment]
Try using ******--devcms.cs13.my.salesforce.com as the instance argument.
Also, using -i test should open a login page at test.salesforce.com.  One
other factor may be how you have configured My Domain. I haven't tried, but
it can be configure to limit logins to the my domain url as opposed to
login or test.salesforce.com.  Could also be that.

On Tue, Mar 1, 2016 at 9:32 AM, Daniel Sokolowski <notifications@github.com>
wrote:

> Yes, triple checked, and if I go the
> https://******--devcms.cs13.my.salesforce.com directly in my browser and
> try to login using my username and password (no token) it works.
>
> On 2016-03-01 12:25 PM, Dave Carroll wrote:
> > Are you using a sandbox username?
> >
> > Dave Carroll
> >
> > On Mar 1, 2016, at 6:17 AM, Daniel Sokolowski <notifications@github.com>
> > wrote:
> >
> > Hello all,
> >
> > Need to confirm what the expected behavior is, I have the latest
> > force_windows_386.exe and I can't figure out how to login.
> >
> > 1.
> >
> > When I do force_windows_386.exe login -i=test a browser window open up
> > to the salesforce login page but I can not login, tried username with
> > pass,
> > and username with passtoken
> > 2.
> >
> > When I do force_windows_386.exe login -i=*********--
> > devcms.cs13.my.salesforce.com I get ERROR: no such endpoint type
> > 3.
> >
> > When I do force login -u=daniel.sokolowski@stantive.com.devcms
> > -p=<passandtoken> it does login.
> >
> > Why is approach 1 not working?, why is option 2 giving me no such
> > endpoint,
> > I'd like to make a small script to send to the client so the ideal
> > would be
> > for them to login using option 1.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/heroku/force/issues/263>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/heroku/force/issues/263#issuecomment-190822780>.
> >
>
> --
> Daniel Sokolowski
> http://webdesign.danols.com/
> Office: 613-817-6833
> Kingston, ON K7L 1H3, Canada
>
>
> Notice of Confidentiality:
> The information transmitted is intended only for the person or entity to
> which it is addressed
> and may contain confidential and/or privileged material. Any review
> re-transmission dissemination
> or other use of or taking of any action in reliance upon this information
> by persons or entities
> other than the intended recipient is prohibited. If you received this in
> error please contact
> the sender immediately by return electronic transmission and then
> immediately delete this
> transmission including all attachments without copying distributing or
> disclosing same.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/263#issuecomment-190825208>.
>



-- 
Thanks,
Dave

**Comment by timothywlewis** [comment]
The problem for me ended up being an expired password. After resetting the password on the account `force login` worked.
